ALTER TYPE "AgentEventType" ADD VALUE IF NOT EXISTS 'HUMAN_APPROVAL_CREATED';
ALTER TYPE "AgentEventType" ADD VALUE IF NOT EXISTS 'TICKET_STATUS_CHANGED';
ALTER TYPE "AgentEventType" ADD VALUE IF NOT EXISTS 'TICKET_PRIORITY_CHANGED';
